/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * start.java
 *
 * Created on 6-set-2011, 17.30.00
 */

package views;

import control.*;
import interfacce_remote.control.*;
import interfacce_remote.entity.ClienteInterface;
import interfacce_remote.entity.DescrizioneInterface;
import interfacce_remote.entity.FilmInterface;
import interfacce_remote.entity.FormatoInterface;
import interfacce_remote.entity.GenereInterface;
import interfacce_remote.entity.TerminaleInterface;
import interfacce_remote.entity.TransizioneInterface;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import vrms_client.Main;



import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Antonio
 */
public class NoleggioView extends javax.swing.JPanel {
    private Main PagePanel;
    private String combo="Tutti";
    private TransizioneInterface transizione;
    private FilmInterface copia;
    private ArrayList <FilmInterface> film;
    private ClienteInterface cliente;
    private float costo;
    private TerminaleInterface terminale;
    private ControllerLoginInterface cl;
    private ControllerNoleggioInterface cn;
    private ControllerRicercaInterface  cr;
   
    /** Creates new form start */
    public NoleggioView(Main PanP) {
        initComponents();
	PagePanel = PanP;

       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel20 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        jLayeredPane1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jLayeredPane1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jLayeredPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLayeredPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrizione Film"));
        jLayeredPane2.setMaximumSize(new java.awt.Dimension(651, 500));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(651, 500));
        jLayeredPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLayeredPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setText("Titolo:");
        jLabel3.setBounds(30, 50, 60, 14);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Genere:");
        jLabel4.setBounds(30, 70, 60, 14);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Anno:");
        jLabel5.setBounds(30, 90, 60, 14);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Durata:");
        jLabel6.setBounds(30, 110, 60, 14);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Costo:");
        jLabel7.setBounds(30, 130, 60, 20);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("<Genere>");
        jLabel9.setBounds(110, 70, 110, 14);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("<Anno>");
        jLabel10.setBounds(110, 90, 110, 14);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("<Durata>");
        jLabel11.setBounds(110, 110, 120, 14);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setText("<Costo>");
        jLabel12.setBounds(110, 130, 120, 20);
        jLayeredPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel13.setBounds(340, 20, 300, 250);
        jLayeredPane2.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setText("<Titolo>");
        jLabel14.setBounds(110, 40, 90, 30);
        jLayeredPane2.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane2.setBounds(20, 280, 610, 160);
        jLayeredPane2.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Cambia Film");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(500, 460, 130, 30);
        jLayeredPane2.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(20, 190, 650, 500);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("<Tessera Non Identificata>");

        jLabel15.setText("Inserisci Tessera");

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel17.setText("jLabel17");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBounds(20, 150, 1330, 30);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Noleggia Copia"));
        jLayeredPane3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLayeredPane3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Seleziona Formato");
        jLabel1.setBounds(10, 50, 110, 20);
        jLayeredPane4.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Costo Formato");
        jLabel2.setBounds(10, 80, 120, 20);
        jLayeredPane4.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel18.setBounds(130, 80, 110, 0);
        jLayeredPane4.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel19.setBounds(250, 50, 370, 0);
        jLayeredPane4.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.setBounds(130, 50, 130, 20);
        jLayeredPane4.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setBounds(270, 50, 350, 20);
        jLayeredPane4.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.setText("Nessun Formato Selezionato");
        jLabel25.setBounds(130, 80, 200, 20);
        jLayeredPane4.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("Prenota Copia");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(370, 80, 140, 30);
        jLayeredPane4.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBounds(20, 30, 630, 170);
        jLayeredPane3.add(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setText("Numero giorni del noleggio");
        jLabel20.setBounds(10, 54, 140, 30);
        jLayeredPane5.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSpinner1.setEnabled(false);
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.setBounds(180, 50, 40, 30);
        jLayeredPane5.add(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setText("Costo Noleggio");
        jLabel21.setBounds(10, 110, 130, 20);
        jLayeredPane5.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("0.0");
        jLabel22.setBounds(170, 100, 40, 40);
        jLayeredPane5.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel23.setBounds(250, 110, 370, 20);
        jLayeredPane5.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Noleggia");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(523, 223, 100, 30);
        jLayeredPane5.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSpinner2.setBounds(180, 60, -1, -1);
        jLayeredPane5.add(jSpinner2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane5.setBounds(20, 220, 630, 260);
        jLayeredPane3.add(jLayeredPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(680, 190, 670, 500);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("XYZVideo");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_company.png"))); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(556, 556, 556))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBounds(20, 20, 1330, 120);
        jLayeredPane1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLayeredPane1AncestorAdded
        // TODO add your handling code here:

          jSpinner1.setValue(0);
          jSpinner1.setEnabled(false);
          jLabel24.setText("");
          jLabel22.setText("");
          jButton4.setVisible(false);

    }//GEN-LAST:event_jLayeredPane1AncestorAdded
    private void VisualizzaGeneri() throws Exception{
        jComboBox1.removeAllItems();
        ComboBoxItem itVuoto = new ComboBoxItem();
        itVuoto.setChiave("");
        itVuoto.setValore("Tutti");
        jComboBox1.addItem(itVuoto);
        List<GenereInterface> generi = new ArrayList();
       
        generi = cr.listaGeneri();
        Iterator iter = generi.iterator();
        int i =0;
        
        while (iter.hasNext()) {
            ComboBoxItem it = new ComboBoxItem();
            Object key = iter.next();
            it.setValore(generi.get(i).getNome());
            it.setChiave("");
            jComboBox1.addItem(it);
            i++;
        }
    }
    private void jLayeredPane1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLayeredPane1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLayeredPane1CaretPositionChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        PagePanel.activeView("StartView");
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
            try {
                // TODO add your handling code here:
                cl.Logout(ControllerFactoryClient.getInstance().getTerminale());
            } catch (RemoteException ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            PagePanel.activeView("HomeView");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLayeredPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLayeredPane2AncestorAdded

        try {
            cl=ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerLogin();
            cr=ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerRicerca();
            cn=ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerNoleggio();
            cn.setNoleggio(null,ControllerFactoryClient.getInstance().getTerminale());
            DescrizioneInterface d;
            transizione=cn.NuovaTransizione();
            try {
                cliente = cl.getCliente(ControllerFactoryClient.getInstance().getTerminale());
                // transizione.setTessera(cliente.getTessera_personale());
                int nn = cl.getN_noleggi(ControllerFactoryClient.getInstance().getTerminale());
                jLabel8.setText(cliente.getNome() + " " + cliente.getCognome());
                jTextField2.setVisible(false);
                jButton3.setText("Logout");
                String id_t = cliente.getTessera_personale().getCodice();
                jLabel15.setText("Credito Residuo: " + cliente.getTessera_personale().getCredito() + "    Noleggi aperti: " + nn);
                jLabel17.setText("");
                terminale = cn.CaricaTerminale();
            } catch (Exception ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                film = cn.OttieniCopie(cr.getDesc(ControllerFactoryClient.getInstance().getTerminale()).getID());
            } catch (Exception ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                d = cn.OttieniDescrizione(cr.getDesc(ControllerFactoryClient.getInstance().getTerminale()).getID());
                jLabel14.setText(d.getTitolo());
                jLabel9.setText(d.getGenere().getNome());
                jLabel10.setText(String.valueOf(d.getAnno()));
                jLabel11.setText(String.valueOf(d.getDurata()));
                jLabel12.setText(String.valueOf(d.getCosto()));
                jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource(d.getLocandina())));
                jTextArea1.setText(d.getTrama());
            } catch (Exception ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        } 

    }//GEN-LAST:event_jLayeredPane2AncestorAdded

    private void jLayeredPane3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLayeredPane3AncestorAdded
       
        jButton4.setVisible(false);
        try {
            // TODO add your handling code here:
            VisualizzaFormati();
        } catch (Exception ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLayeredPane3AncestorAdded

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        
        if (evt.getStateChange() == ItemEvent.SELECTED && !((ComboBoxItem) evt.getItem()).getValore().equals("Nessuna Selezione")) {
             combo = ((ComboBoxItem) evt.getItem()).getValore();

            try {
                jLabel25.setText(String.valueOf(cn.OttieniCostoFormato(combo)));
           
                int c=CercaCopia();
               
                if (c==0)
                {

                    int ris= JOptionPane.showConfirmDialog(PagePanel, "Film momentaneamente non disponibile nel formato selezionato.Vuoi prenotare una copia?", "Attenzione", JOptionPane.YES_NO_OPTION);
                    if (ris==JOptionPane.YES_OPTION )
                    {
                    try {
                         ControllerPrenotazioneInterface cp = ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerPrenotazione();
                        try {
                            cp.setFormato(combo);
                            System.out.print(cp.getFormato());
                        } catch (Exception ex) {
                            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        PagePanel.activeView("PrenotazioneView");

                    } catch (RemoteException ex) {
                        Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NotBoundException ex) {
                        Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                 }}
                 else
                {
                      jLabel24.setText("");
                      jButton1.setText("Noleggia");
                      jSpinner1.setEnabled(true);
                      jButton4.setVisible(false);
                    }
                
            } catch (Exception ex) {
                Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else{

                   jLabel25.setText("Nessun formato selezionato");


        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int n = (Integer) jSpinner1.getValue();
        try {
            
            transizione.setFilm_noleggiato(copia);
        } catch (Exception ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        }
     
            try {
                transizione.setTessera(cl.getCliente(ControllerFactoryClient.getInstance().getTerminale()).getTessera_personale());
            } catch (RemoteException ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        try {
            costo = cn.CalcolaTotale(ControllerFactoryClient.getInstance().getTerminale(),transizione, n);
        } catch (Exception ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        } 
        jLabel22.setText(String.valueOf(costo));
        try {
            if (cliente.getTessera_personale().getCredito() < costo) {
                jLabel23.setForeground(new java.awt.Color(255, 0, 0));
                jLabel22.setForeground(new java.awt.Color(255, 0, 0));
                jLabel23.setText("ATTENZIONE! Non hai credito sufficiente");
                jButton1.setEnabled(false);
            } else {
                jLabel23.setForeground(new java.awt.Color(0, 0, 0));
                jLabel22.setForeground(new java.awt.Color(0, 0, 0));
                jLabel23.setText("");
                jButton1.setEnabled(true);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText().equals("Noleggia")){
            try {
                try {
                    transizione.setTessera(cliente.getTessera_personale());
                } catch (RemoteException ex) {
                    Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                }
                transizione.setOrigine_noleggio(terminale);
                transizione.setTipo("noleggio");
                Date data_inizio = new Date();
                transizione.setData_inizio(data_inizio);
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(data_inizio);
                calendar.add(Calendar.DATE, (Integer) jSpinner1.getValue());
                Date data_fine = calendar.getTime();
                transizione.setData_fine(data_fine);
                try {
                    costo = cn.CalcolaTotale(ControllerFactoryClient.getInstance().getTerminale(),transizione, (Integer) (jSpinner1.getValue()));
                } catch (Exception ex) {
                    Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                }
                transizione.setCosto_totale(costo);
                transizione.setAperto(true);
                
                try {
                    System.out.print(ControllerFactoryClient.getInstance().getTerminale());
                     cn.ConfermaNoleggio(ControllerFactoryClient.getInstance().getTerminale(),transizione, costo);
                } catch (Exception ex) {
                    Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                
               }
               
                try {
                    cl.setN_noleggi(1);
                } catch (RemoteException ex) {
                    Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
                }
                //PagePanel.activeView("RiepilogoView");
            } catch (RemoteException ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
             ControllerPrenotazioneInterface cp = ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerPrenotazione();
            try {
                cp.setFormato(combo);
                System.out.print(cp.getFormato());
            } catch (Exception ex) {
                Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            PagePanel.activeView("PrenotazioneView");
           
        } catch (RemoteException ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(NoleggioView.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        PagePanel.activeView("HomeView");
}//GEN-LAST:event_jLabel26MouseClicked
 
     private void VisualizzaFormati() throws Exception{

        jComboBox1.removeAllItems();
        ComboBoxItem itVuoto = new ComboBoxItem();
        itVuoto.setChiave("");
        itVuoto.setValore("Nessuna Selezione");
        jComboBox1.addItem(itVuoto);
        ArrayList<FormatoInterface> elenco_formati;
       
        elenco_formati= cn.OttieniFormati(cr.getDesc(ControllerFactoryClient.getInstance().getTerminale()).getID());

        Iterator iter = elenco_formati.iterator();
        int i =0;

        while (iter.hasNext()) {
            ComboBoxItem it = new ComboBoxItem();
            Object key = iter.next();
            //it.setChiave((String) key);
            it.setValore(elenco_formati.get(i).getNome_formato());
            it.setChiave("");
            jComboBox1.addItem(it);
            i++;
        }}

    private int CercaCopia() throws RemoteException, Exception {
       int r=0;
       Iterator iter= film.iterator();
       boolean trovato=false;
       int i=0;
           
       while(iter.hasNext() && trovato==false)
         {  Object key = iter.next();
            if(film.get(i).getFormato_film().getNome_formato().equalsIgnoreCase(combo) && ! cn.ControllaCopia(film.get(i)))
            {
                r = film.get(i).getID();
                trovato=true;
                copia=film.get(i);
                cn.BloccaCopia(ControllerFactoryClient.getInstance().getTerminale(),film.get(i).getORMID());
                
            }
            i++;
        }
              
       return r;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}


