/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * start.java
 *
 * Created on 6-set-2011, 17.30.00
 */

package views;

import control.ControllerFactoryClient;
import interfacce_remote.control.ControllerLoginInterface;
import interfacce_remote.control.ControllerRicercaInterface;
import interfacce_remote.entity.ClienteInterface;
import interfacce_remote.entity.DescrizioneInterface;
import interfacce_remote.entity.GenereInterface;
import interfacce_remote.entity.ProdottoInterface;
import interfacce_remote.entity.TerminaleInterface;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import vrms_client.Main;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/**
 *
 * @author Antonio
 */
public class StartView extends javax.swing.JPanel {
    private Main PagePanel;
    private String combo="Tutti";
    private  DescrizioneInterface descrizione;
    private ProdottoInterface ap;
    private int nn;
    private ClienteInterface cliente;
    private  ArrayList <DescrizioneInterface> risultato;
    private boolean aux = false;
    private int t;
    private ControllerLoginInterface cl;
    private ControllerRicercaInterface cr;
    static Logger logger=Logger.getLogger("global");

     /** Creates new form start */
    public StartView(Main PanP,String s) {
        initComponents();
	PagePanel = PanP;
      }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLayeredPane1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jLayeredPane1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jLayeredPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLayeredPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Elenco"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.setBounds(20, 340, 651, 350);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ricerca Film"));

        jButton1.setText("Cerca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Titolo");

        jLabel2.setText("Genere");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(229, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 180, Short.MAX_VALUE))))
                .addGap(349, 349, 349))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBounds(20, 190, 651, 150);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrizione Film"));
        jLayeredPane2.setMaximumSize(new java.awt.Dimension(651, 500));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(651, 500));

        jLabel3.setText("Titolo:");
        jLabel3.setBounds(30, 50, 60, 14);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Genere:");
        jLabel4.setBounds(30, 70, 60, 14);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Anno:");
        jLabel5.setBounds(30, 90, 50, 14);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Durata:");
        jLabel6.setBounds(30, 110, 60, 14);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Costo:");
        jLabel7.setBounds(30, 130, 60, 14);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("<Genere>");
        jLabel9.setBounds(110, 70, 130, 14);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("<Anno>");
        jLabel10.setBounds(110, 90, 120, 14);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("<Durata>");
        jLabel11.setBounds(110, 110, 120, 14);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setText("<Costo>");
        jLabel12.setBounds(110, 130, 90, 14);
        jLayeredPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel13.setBounds(340, 20, 310, 250);
        jLayeredPane2.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setText("<Titolo>");
        jLabel14.setBounds(110, 40, 140, 30);
        jLayeredPane2.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane2.setBounds(20, 280, 640, 170);
        jLayeredPane2.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Procedi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(569, 460, 90, 30);
        jLayeredPane2.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel22.setBounds(10, 20, 650, 230);
        jLayeredPane2.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(680, 190, 670, 500);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("<Tessera Non Identificata>");

        jLabel15.setText("Inserisci Tessera");

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(821, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBounds(20, 150, 1330, 30);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("XYZVideo");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_company.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(556, 556, 556))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBounds(20, 20, 1330, 120);
        jLayeredPane1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLayeredPane1AncestorAdded
        try {
            // TODO add your handling code here:
            if (descrizione == null)
            {   jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Latosx.png"))); 
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel14.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                jLabel11.setVisible(false);
                jLabel12.setVisible(false);
                jLabel13.setVisible(false);
                jTextArea1.setVisible(false);
            }
            else
            {   jLabel22.setVisible(false);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel14.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
                jLabel11.setVisible(true);
                jLabel12.setVisible(true);
                jLabel13.setVisible(true);
                jTextArea1.setVisible(true);
            }
            cl = ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerLogin();
            cr = ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerRicerca();
            cliente = cl.getCliente(ControllerFactoryClient.getInstance().getTerminale());
            
            if (cliente != null) {
                try {
                    nn = cl.contaNoleggi(cliente.getTessera_personale().getCodice());
                } catch (Exception ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
              jTextField1.setText(cr.getOrdine(ControllerFactoryClient.getInstance().getTerminale()));
            if (! jTextField1.getText().equals("")) 
            {
                try {
                    risultato = cr.CercaFilm(jTextField1.getText(), combo);
                    if (risultato.isEmpty()) {
                        
                        jButton1.setEnabled(false);
                    } else {
                       
                        jButton1.setEnabled(true);
                    }
                    RiempiTabella(risultato);
                } catch (Exception ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (cliente != null) {
                jTextField2.setVisible(false);
                jButton3.setText("Logout");
            } else {
                jTextField2.setVisible(true);
                jButton3.setText("Login");
            }
           
            jLabel18.setText("");
           
            jButton1.setEnabled(true);
            try {
                risultato = cr.caricaCatalogo();
                if (cliente != null) {
                    jLabel8.setText(cliente.getNome() + " " + cliente.getCognome());
                    jLabel15.setText("Credito Residuo: " + cliente.getTessera_personale().getCredito() + "    Noleggi aperti: " + nn);
                } else {
                    jLabel8.setText("Tessera Non Identificata");
                    jTextField2.setVisible(true);
                    jButton3.setText("Login");
                    jLabel15.setText("InserisciTessera");
                    jTextField2.setText("");
                }
            } catch (Exception ex) {
                Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
            }
            RiempiTabella(risultato);
            try {
                VisualizzaGeneri();
            } catch (Exception ex) {
                Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLayeredPane1AncestorAdded

    private void VisualizzaGeneri() throws Exception{
        jComboBox1.removeAllItems();
        ComboBoxItem itVuoto = new ComboBoxItem();
        itVuoto.setChiave("");
        itVuoto.setValore("Tutti");
        jComboBox1.addItem(itVuoto);
        List<GenereInterface> generi = new ArrayList();
        cr = ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerRicerca();
        generi = cr.listaGeneri();
        Iterator iter = generi.iterator();
        int i =0;
        
        while (iter.hasNext()) {
            ComboBoxItem it = new ComboBoxItem();
            Object key = iter.next();
            //it.setChiave((String) key);
            it.setValore(generi.get(i).getNome());
            it.setChiave("");
            jComboBox1.addItem(it);
            i++;
        }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        jLabel18.setVisible(false);
    
        jButton1.setEnabled(true);
        if (evt.getStateChange() == ItemEvent.SELECTED && !((ComboBoxItem) evt.getItem()).getValore().equals("Tutti")) {
            combo=((ComboBoxItem) evt.getItem()).getValore();
            try {
                ArrayList<DescrizioneInterface> tabella;
                tabella=cr.elencoPerGenere(((ComboBoxItem) evt.getItem()).getValore());
                RiempiTabella(tabella);
                //comboBoxTessuto.setEnabled(false);
            } catch (Exception ex) {
                Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else{
            try  {
                   risultato = cr.caricaCatalogo();
                   RiempiTabella(risultato);
         } catch (Exception ex) {
            Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try {
       
           risultato= cr.CercaFilm(jTextField1.getText(), combo);
           if (risultato.isEmpty())
             {
                  /*jLabel19.setVisible(true);
                  jLabel20.setVisible(true);
                  jButton4.setVisible(true);
                  jButton5.setVisible(true);*/
                  int ris= JOptionPane.showConfirmDialog(PagePanel, "Film non presente in questa videoteca. Vuoi Ordinarlo?", "Attenzione", JOptionPane.YES_NO_OPTION);
                  if (ris==JOptionPane.YES_OPTION )

                     {
                        
                        if (cliente != null)
                             {  

                            try {

                                 TerminaleInterface t= cr.CaricaTerminale();
                                 ArrayList <ProdottoInterface> ap1 = cr.CatalogoFilmOrdinabili(jTextField1.getText());
                                
                                if(ap1.size()!=0){
                                    System.out.print(ap1.size());
                                    RiempiTabella2(ap1);
                                    jLabel18.setVisible(true);
                                    jLabel18.setText("Seleziona il film che vuoi ordinare!");
                                 }
                                 else {
                                    /* jLabel18.setVisible(true);
                                     jLabel18.setText("Non sono stati trovati film con il titolo inserito!");
                                     jLabel18.setForeground(Color.red);*/

                                      JOptionPane.showMessageDialog(PagePanel, "Non sono stati trovati film con il titolo inserito! Rivolgersi alla cassa", "Attenzione", JOptionPane.ERROR_MESSAGE);

                                 }

                           } catch (Exception ex) {
                                Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                            }

                                     }
                                else
                                    {  /* jLabel17.setForeground(Color.red);
                                        jLabel17.setText("ATTENZIONE! Devi essere loggato per poter effettuare un ordine");*/
                                        JOptionPane.showMessageDialog(PagePanel, "Devi essere loggato per poter effettuare un ordine", "Attenzione", JOptionPane.ERROR_MESSAGE);
                                     }

                                              }
                              }
           else
             {
               
                  jButton1.setEnabled(true);
                 RiempiTabella(risultato);}
          
        } catch (Exception ex) {
            Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            JTable table = (JTable) evt.getSource();
            

            int rigacliccata = table.rowAtPoint(evt.getPoint());
            cr = ControllerFactoryClient.getInstance().getFornitoreInterface().getControllerRicerca();

            if(!aux){
                jLabel22.setVisible(false);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel14.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
                jLabel11.setVisible(true);
                jLabel12.setVisible(true);
                jLabel13.setVisible(true);
                jTextArea1.setVisible(true);
                String id = jTable1.getValueAt(rigacliccata, 0).toString();
                descrizione = cr.ottieniFilm(Integer.valueOf(id));
          
                jLabel18.setText("");
                jLabel14.setText(descrizione.getTitolo());
                jLabel9.setText(descrizione.getGenere().getNome());
                int a= descrizione.getAnno();
                String b=String.valueOf(a);
                jLabel10.setText(b);
                jLabel11.setText(descrizione.getDurata());
                jLabel12.setText(String.valueOf(descrizione.getCosto()));
                jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource(descrizione.getLocandina())));
                cr.setDesc(descrizione,ControllerFactoryClient.getInstance().getTerminale());
                jTextArea1.setText(descrizione.getTrama());
            }
         else{
                jLabel22.setVisible(false);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel14.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
                jLabel11.setVisible(true);
                jLabel12.setVisible(true);
                jLabel13.setVisible(true);
                jTextArea1.setVisible(true);
                t = Integer.valueOf(jTable1.getValueAt(rigacliccata, 0).toString());
                ap = cr.ottieniFilmOrdinato(t);
                
                jLabel18.setText("");
                jLabel14.setText(ap.getTitolo());
                jLabel9.setText(ap.getGenere());
                int a= ap.getAnno();
                String b=String.valueOf(a);
                jLabel10.setText(b);
                jLabel11.setText("");
                jLabel12.setText("");
                jLabel13.setText("");
                jLabel6.setText("");
                jLabel7.setText("");
                jTextArea1.setText("");
         }
            
          // dispose();
        } catch (Exception ex) {
            Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLayeredPane1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLayeredPane1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLayeredPane1CaretPositionChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       
        if(!aux){
        if(cliente == null)
           {
         
             /*jLabel17.setForeground(Color.red);
             jLabel17.setText("ATTENZIONE!Prima di Proseguire con il noleggio è necessario inserire la propria tessera");
                   */
             JOptionPane.showMessageDialog(PagePanel, "Prima di Proseguire con il noleggio è necessario inserire la propria tessera", "Attenzione", JOptionPane.ERROR_MESSAGE);

        }
         else 
                try {
                    if (cr.getDesc(ControllerFactoryClient.getInstance().getTerminale()) == null) {
                        jLabel18.setForeground(Color.red);
                        jLabel18.setText("ATTENZIONE!Prima di Proseguire con il noleggio è necessario selezionare un film");
                    } else if (nn >= 3) {

                        JOptionPane.showMessageDialog(PagePanel, "Hai già noleggiato tre film, effettua prima una restituzione!", "Attenzione", JOptionPane.ERROR_MESSAGE);

                       /* jLabel17.setForeground(Color.red);
                        jLabel17.setText("ATTENZIONE! ");*/
                    } else {
                        PagePanel.activeView("NoleggioView");
                    }
                } catch (RemoteException ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
        else{
           if(cliente == null)
           {

                    JOptionPane.showMessageDialog(PagePanel, "Prima di Proseguire con l'ordine è necessario inserire la propria tessera", "Attenzione", JOptionPane.ERROR_MESSAGE);

            /*jLabel17.setForeground(Color.red);
             jLabel17.setText("ATTENZIONE!Prima di Proseguire con l'ordine è necessario inserire la propria tessera");
               */     }
        
        
           else {
                try {
                    cr.CreaOrdine(t, cliente.getTessera_personale().getCodice(), cr.CaricaTerminale());
                } catch (Exception ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                }
               
               PagePanel.activeView("OrdineView");
                 }
                
           }

        
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
      
        if(jButton3.getText().equals("Login")){
        
        try {
            
           cl.Login(jTextField2.getText(),ControllerFactoryClient.getInstance().getTerminale());
           cliente=cl.getCliente(ControllerFactoryClient.getInstance().getTerminale());
           nn=cl.getN_noleggi(ControllerFactoryClient.getInstance().getTerminale());
            if (cliente != null)
                {   
                    jTextField2.setVisible(false);
                    jButton3.setText("Logout");
                    
                    String id_t= cliente.getTessera_personale().getCodice();
                    nn = cl.contaNoleggi(id_t);
                    jLabel8.setText(cliente.getNome() +" " +cliente.getCognome());
                    jLabel15.setText("Credito Residuo: "+ cliente.getTessera_personale().getCredito()+"    Noleggi aperti: "+nn);
                }
            else
                {
                    JOptionPane.showMessageDialog(PagePanel, "Tessera non riconosciuta. Riprovare oppure rivolgersi alla cassa", "Attenzione", JOptionPane.ERROR_MESSAGE);

                    }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(PagePanel, ex.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        }
        else
         {          jLabel8.setText("Tessera Non Identificata");
                    jTextField2.setVisible(true);
                    jButton3.setText("Login");
                    jLabel15.setText("InserisciTessera");
                    jTextField2.setText("");
            
                try {
                    cl.Logout(ControllerFactoryClient.getInstance().getTerminale());
                } catch (RemoteException ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(StartView.class.getName()).log(Level.SEVERE, null, ex);
                }
           
                   
                    PagePanel.activeView("HomeView");
                   

       }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        PagePanel.activeView("HomeView");
}//GEN-LAST:event_jLabel21MouseClicked
 private void RiempiTabella(ArrayList<DescrizioneInterface> des) throws RemoteException{
        String[] header = {"ID","Titolo","Genere"};
        Object[][] data= new Object[des.size()][header.length];
        aux = false;
        Iterator it =des.iterator();
        int i=0;
        DescrizioneInterface d;
        while (it.hasNext())
        {d=((DescrizioneInterface)it.next());
            data[i][0]=d.getORMID();
            data[i][1]=d.getTitolo();
            data[i][2]=d.getGenere().getNome();
            //data[i][3]=d.getAnno();
            //data[i][4]=d.getDurata();
            //data[i][5]=d.getCosto();
        i++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));
    }
    
     private void RiempiTabella2(ArrayList<ProdottoInterface> ap) throws RemoteException {

        String[] header = {"ID","Titolo","Genere","Anno","Formato"};
        Object[][] data= new Object[ap.size()][header.length];
        aux = true;
        Iterator it =ap.iterator();
        int i=0;
        ProdottoInterface  d;
       
        while (it.hasNext())
        {   d=((ProdottoInterface)it.next());
            data[i][0]=d.getID();
            data[i][1]=d.getTitolo();
            data[i][2]=d.getGenere();
            data[i][3]=d.getAnno();
            data[i][4]=d.getFormato();
            //data[i][5]=d.getCosto();
        i++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

   

}




