/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package vrms_cassiere;

import interfacce_remote.entity.TerminaleInterface;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Antonio
 */
public class Main extends javax.swing.JFrame {
     private CardLayout cardLayout;
     private String appoggio;
     private static TerminaleInterface terminale;
    /** Creates new form Main */
    public Main() {
        initComponents();
        PagePanel.setLayout(cardLayout);



    }

    public static TerminaleInterface getTerminale() {
        return terminale;
    }

    public static void setTerminale(TerminaleInterface terminale) {
        Main.terminale = terminale;
    }

    private void focus(TextField p) {


        addWindowListener( new WindowAdapter() {
        public void windowOpened( WindowEvent e ){
        // p.requestFocus();
      }
    } );



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        cardLayout = new CardLayout();
        PagePanel = new javax.swing.JPanel(cardLayout);

        setTitle("VRMS v1.0");
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PagePanel.add(new views.CassiereHomeView(this),"CassiereHomeView");
        PagePanel.add(new views.NuovoClienteView(this),"NuovoClienteView");
        PagePanel.add(new views.ModificaClienteView(this),"ModificaClienteView");
        PagePanel.add(new views.EliminaClienteView(this),"EliminaClienteView");
        PagePanel.add(new views.RicaricaTesseraView(this),"RicaricaTesseraView");
        PagePanel.add(new views.RiepilogoNuovoClienteView(this),"RiepilogoNuovoClienteView");
        PagePanel.add(new views.RiepilogoModificaClienteView(this),"RiepilogoModificaClienteView");
        PagePanel.add(new views.RiepilogoEliminaClienteView(this),"RiepilogoEliminaClienteView");
        PagePanel.add(new views.RiepilogoRicaricaTesseraView(this),"RiepilogoRicaricaTesseraView");
        PagePanel.setBackground(new java.awt.Color(0, 0, 0));
        PagePanel.setPreferredSize(new java.awt.Dimension(1362, 690));

        PagePanel.setLayout(new java.awt.CardLayout());
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();}

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here




          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);


            }
        });
    }



  private javax.swing.JPanel PagePanel;
    // End of variables declaration
    public void activeView(String p) {


        cardLayout.show(PagePanel, p);
        cardLayout.getClass();

    }


}


